from src.schema.question.response_example.get_by_id import get_by_id_response_example
from src.schema.question.response_example.get_multi import get_multi_response_example
from src.schema.question.response_example.create import create_response_example
from src.schema.question.response_example.update import update_response_example
from src.schema.question.response_example.delete import delete_response_example